apiVersion: v1
kind: Namespace
metadata:
  name: hackathon-ui-2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hackathon-ui-user-2
  namespace: hackathon-ui-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-ui-deployment-2
  namespace: hackathon-ui-2
  labels:
    app: hackathon-ui-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hackathon-ui-2
  template:
    metadata:
      labels:
        app: hackathon-ui-2
    spec:
      serviceAccountName: hackathon-ui-user-2
      containers:
        - name: hackathon-ui-2
          image: cagip/hackathon-ui:latest
          imagePullPolicy: Always
          env:
            - name: VUE_APP_API_ENDPOINT
              value: 'http://<public_ip_hackathon-api>'
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              scheme: HTTP
              port: 80
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              scheme: HTTP
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hackathon-ui-svc-2
  namespace: hackathon-ui-2
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: hackathon-ui-2
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: hackathon-ui-2